path:
  ckpt_path: "./output/ckpt/AD_Lips_Pred_postnet_pred_aperture_spreading"
  log_path: "./output/log/AD_Lips_Pred_postnet_pred_aperture_spreading"
  result_path: "./output/result/AD_Lips_Pred_postnet_pred_aperture_spreading"
  train_csv_path: "train_AD_neutral_FS.txt"
  val_csv_path: "test_AD_neutral_FS.txt"
optimizer:
  batch_size: 32
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 12000
  anneal_steps: [20000, 30000, 35000]
  anneal_rate: 0.3
step:
  total_step: 40000
  log_step: 100
  synth_step: 1000
  val_step: 5000
  save_step: 10000
output:
  wav: False
